### ISSUE TITLE
maze.py

### ISSUE THREAD

**Issue by iannellog** [FioroniCostanza/labyrinth_22-23#1]
Il codice è scritto in modo tale che non si capisce facilmente quali sono gli attributi della classe (che dovrebbero essere: self.maze, self.start, self.end). Questo perché essi non vengoono creati nel costruttore, ma in altri metodi. Bisognerebbe invece che guardando il solo costruttore sia evidente quale è la *rappresentazione* della classe (cioé quali sono gli attributi che contengono i dati che caratterizzano il comportamento di un'istanza della classe).

Inoltre, vengono creati attributi che in realtà non fanno parte della rappresentazione. 
Per esempio l'attributo self.image nel metodo load_maze. Tale attributo può essere facilmente eliminato se si adotta la stessa tecnica usata per i file JSON (righe 40-43). In altre parole così come il metodo json_to_maze ha il parametro data, analogamente il metodo image_to_maze potrebbe avere il parametro image evitando di passare il descrittore del file in modo implicito attraverso la creazione di un attributo che in realtà non serve.
Un discorso analogo si potrebbe fare per gli attributi creati nel costruttore che, ancora una volta non sarebbero veri attributi e potrebbero semplicemente essere passati come parametri a load_maze.

I risultati dei metodi (frase return finale) non sembrano adeguati e in alcuni casi non sono documentati correttamente nel commento iniziale. In effetti ciò che viene restituito non viene quasi mai utilizzato dal chiamante per cui ci si può chiedere a che serve.

**Comment by danielemolino** [comment]
Buon Pomeriggio professore,
Ho appena provveduto a modificare la classe Maze eliminando alcuni attributi superflui e quei return che effettivamente non servivano a nulla dato che i vari metodi lavorano sugli attributi. 

Ho deciso però di mantenere oltre a Maze Start ed End anche l'attributo image della classe Maze poiché nella mia idea della classe l'immagine è caratterizzante del labirinto, soprattutto nel caso in ingresso si abbia un file Json.
Anche perché poi mi serve passarla alla funzione che genera gli output.

Analogamente ho cercato di ripetere questa ottimizzazione anche per la classe Path, poiché secondo me gli unici attributi che dovrebbero esserci sono Paths e Weight, mentre al momento avevamo anche gli attributi Maze Start ed End, che ho provveduto ad eliminare.
