### ISSUE TITLE
path.py

### ISSUE THREAD

**Issue by iannellog** [FioroniCostanza/labyrinth_22-23#3]
Il metodo get_adjacent_positions dovrebbe concettualmente essere un  metodo della classe Maze.
In tal modo la rappresentazione di un oggetto della classe Maze è meglio incapsulato (con la soluzione attuale la classe Path d fatto manipola direttamente la rappresentazione di un oggetto della classe Maze).

**Comment by stefanoperone01** [comment]
Salve,
ho risolto il tutto passando alla classe Path come parametro di ingresso una sola variabile riferita alla classe Maze in modo tale da poter passare tutte le informazioni necessarie tramite essa.
In tal modo il metodo della classe Path che calcola il percorso, ricevendo in ingresso la variabile maze, tramite essa può richiamare il metodo get_adjacent_position che adesso si trova, come richiesto, all'interno della classe Maze
