### ISSUE TITLE
Piccolo errore

### ISSUE THREAD

**Issue by iannellog** [FioroniCostanza/labyrinth_22-23#4]
Se quando si digita il percorso del file di input si aggiungono spazi dopo il path, il programma va in errore perché questi spazi vengono considerati parte del suffisso che qhindi non viene riconosciuto. 
Per risolvere il problema, usate la funzione strip() per rimuovere gli spazi prima e dopo la stringa letta, prima di passarla al coostruttore di Maze.

**Comment by FioroniCostanza** [comment]
Salve Professore, è stato appena modificato inserendo alla fine della funzione input .strip(), come da lei suggerito
