### ISSUE TITLE
Problema con Dijkstra

### ISSUE THREAD

**Issue by iannellog** [FioroniCostanza/labyrinth_22-23#5]
Il vostro programma dà risultati diversi dal mio nel caso del labirinto 'labirinto3b_marked'. Di fatto fornisce percorsi a costo maggiore.
Sospetto che ci sia un problema sul valore che assume la variabile weight nel metodo 'find_shortest_path_by_weight'.
Se ho capito bene, quando a una casella non è associato un costo aggiuntivo, il suo peso risulta 0 (riga 76 nel file maze.py). Se è così, è sbagliato perché a quel punto il costo di un percorso non dipende più dalla sua lunghezza e dijkstra può dare un risultato sbagliato.
Verificate se il mio ragionamento è corretto e nel caso fate in modo che il costo di un percorso siua la somma delle sua lunghezze più gli eventuali costi aggiuntivi associati ad alcune caselle.

**Comment by stefanoperone01** [comment]
Buonasera professore,
il problema è stato risolto con il commit appena effettuato. In tale commit abbiamo modificato il valore del peso delle caselle bianche e portandolo ad 1 (e aumentando di conseguenza di 1 anche il valore di quelle grigie). Adesso infatti, come da lei rilevato, vengono risultati diversi risolvendo il labirinto 'labirinto3b_marked'.
