### ISSUE TITLE
Migliorare .gitignore e README.md

### ISSUE THREAD

**Issue by iannellog** [FioroniCostanza/labyrinth_22-23#6]
Il progetto mi sembra ok: fa tutto quello che è richiesto.
Non so se avevate in mente altre modifiche.

Potreste migliorare il file .gitignore escludendo la directory 'Percorsi'

Suggerisco poi di completare README.md descrivendo brevemente quale comando digitare e che le convenzioni usare per nominare i file di uscita nella directory Percorsi.

**Comment by FioroniCostanza** [comment]
Salve Prof, avevo visto la issue e stavo procedendo nella modifica del README.md, ho solo avuto un problema con il computer e non mi ha salvato nulla. Vado subito a modificare con tutte le informazioni necessarie e escludendo anche la directory ‘Percorsi’ dal file .gitignore
